# Modelo markoviano inicial

Comprendamos los conceptos fundamentales

In [2]:
import numpy as np

np.set_printoptions(precision=6, suppress=True)

# --------------------------------------------------
# 1. Matriz de transición
#    p_ij = P(X_{t+1}=j | X_t=i)
#    Las filas deben sumar 1
# --------------------------------------------------

P = np.array([
    [0.6, 0.3, 0.1],
    [0.2, 0.5, 0.3],
    [0.1, 0.3, 0.6]
])

print("Matriz de transición P:")
print(P)

print("\nSuma de las filas:")
print(P.sum(axis=1))



Matriz de transición P:
[[0.6 0.3 0.1]
 [0.2 0.5 0.3]
 [0.1 0.3 0.6]]

Suma de las filas:
[1. 1. 1.]


In [3]:

# --------------------------------------------------
# 2. Distribución inicial
#    Vector fila
# --------------------------------------------------

# Comenzamos con certeza en el estado 1
pi0 = np.array([1.0, 0.0, 0.0])

print("\nDistribución inicial:")
print(pi0)


# --------------------------------------------------
# 3. Evolución de la distribución
#
#    pi_(t+1) = pi_t P
# --------------------------------------------------

pi = pi0.copy()

print("\nEvolución de la distribución:")

for t in range(11):
    print(f"t={t:2d}: {pi}")
    pi = pi @ P




Distribución inicial:
[1. 0. 0.]

Evolución de la distribución:
t= 0: [1. 0. 0.]
t= 1: [0.6 0.3 0.1]
t= 2: [0.43 0.36 0.21]
t= 3: [0.351 0.372 0.277]
t= 4: [0.3127 0.3744 0.3129]
t= 5: [0.29379 0.37488 0.33133]
t= 6: [0.284383 0.374976 0.340641]
t= 7: [0.279689 0.374995 0.345316]
t= 8: [0.277344 0.374999 0.347657]
t= 9: [0.276172 0.375    0.348828]
t=10: [0.275586 0.375    0.349414]


In [5]:

# --------------------------------------------------
# 4. Potencias de P
#
#    (P^n)_ij =
#    P(X_{t+n}=j | X_t=i)
# --------------------------------------------------

for n in [1, 2, 5, 10, 50, 100]:

    Pn = np.linalg.matrix_power(P, n)

    print(f"\nP^{n}:")
    print(Pn)





P^1:
[[0.6 0.3 0.1]
 [0.2 0.5 0.3]
 [0.1 0.3 0.6]]

P^2:
[[0.43 0.36 0.21]
 [0.25 0.4  0.35]
 [0.18 0.36 0.46]]

P^5:
[[0.29379 0.37488 0.33133]
 [0.27285 0.3752  0.35195]
 [0.26254 0.37488 0.36258]]

P^10:
[[0.275586 0.375    0.349414]
 [0.274935 0.375    0.350065]
 [0.274609 0.375    0.350391]]

P^50:
[[0.275 0.375 0.35 ]
 [0.275 0.375 0.35 ]
 [0.275 0.375 0.35 ]]

P^100:
[[0.275 0.375 0.35 ]
 [0.275 0.375 0.35 ]
 [0.275 0.375 0.35 ]]


In [6]:
# --------------------------------------------------
# 5. Distribución estacionaria por punto fijo
#
#    Iteramos:
#
#       pi_(t+1) = pi_t P
#
#    hasta que:
#
#       pi_(t+1) ≈ pi_t
# --------------------------------------------------

pi = pi0.copy()

tolerancia = 1e-10
max_iteraciones = 10000

for k in range(max_iteraciones):

    pi_nueva = pi @ P

    error = np.max(np.abs(pi_nueva - pi))

    if error < tolerancia:
        break

    pi = pi_nueva


print("\nDistribución estacionaria:")
print(pi_nueva)

print("Iteraciones:", k + 1)
print("Error:", error)


# --------------------------------------------------
# 6. Comprobación del punto fijo
# --------------------------------------------------

print("\nComprobación:")

print("pi:")
print(pi_nueva)

print("pi @ P:")
print(pi_nueva @ P)


Distribución estacionaria:
[0.275 0.375 0.35 ]
Iteraciones: 33
Error: 6.984918199393064e-11

Comprobación:
pi:
[0.275 0.375 0.35 ]
pi @ P:
[0.275 0.375 0.35 ]


# Modelo con estados absorbentes

In [7]:
import numpy as np

np.set_printoptions(precision=6, suppress=True)

# Estados:
# 0 = A  transitorio
# 1 = B  transitorio
# 2 = C  absorbente
# 3 = D  absorbente

estados = ["A", "B", "C", "D"]

# --------------------------------------------------
# 1. Matriz de transición
#
# p_ij = P(X_(t+1)=j | X_t=i)
#
# Las filas son el estado de origen
# Las columnas son el estado de destino
# --------------------------------------------------

P = np.array([
    [0.3, 0.3, 0.3, 0.1],   # desde A
    [0.2, 0.3, 0.1, 0.4],   # desde B
    [0.0, 0.0, 1.0, 0.0],   # C absorbente
    [0.0, 0.0, 0.0, 1.0]    # D absorbente
])

print("Matriz de transición P:")
print(P)

print("\nSuma de las filas:")
print(P.sum(axis=1))



Matriz de transición P:
[[0.3 0.3 0.3 0.1]
 [0.2 0.3 0.1 0.4]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]

Suma de las filas:
[1. 1. 1. 1.]


In [8]:

# --------------------------------------------------
# 2. Distribución inicial
#
# Comenzamos con certeza en A
# --------------------------------------------------

pi0 = np.array([1.0, 0.0, 0.0, 0.0])

print("\nDistribución inicial:")
print(pi0)


# --------------------------------------------------
# 3. Evolución de la cadena
#
# pi_(t+1) = pi_t P
# --------------------------------------------------

pi = pi0.copy()

print("\nEvolución:")

for t in range(15):

    print(
        f"t={t:2d}  "
        f"A={pi[0]:.4f}  "
        f"B={pi[1]:.4f}  "
        f"C={pi[2]:.4f}  "
        f"D={pi[3]:.4f}"
    )

    pi = pi @ P




Distribución inicial:
[1. 0. 0. 0.]

Evolución:
t= 0  A=1.0000  B=0.0000  C=0.0000  D=0.0000
t= 1  A=0.3000  B=0.3000  C=0.3000  D=0.1000
t= 2  A=0.1500  B=0.1800  C=0.4200  D=0.2500
t= 3  A=0.0810  B=0.0990  C=0.4830  D=0.3370
t= 4  A=0.0441  B=0.0540  C=0.5172  D=0.3847
t= 5  A=0.0240  B=0.0294  C=0.5358  D=0.4107
t= 6  A=0.0131  B=0.0160  C=0.5460  D=0.4249
t= 7  A=0.0071  B=0.0087  C=0.5515  D=0.4326
t= 8  A=0.0039  B=0.0048  C=0.5545  D=0.4368
t= 9  A=0.0021  B=0.0026  C=0.5562  D=0.4391
t=10  A=0.0012  B=0.0014  C=0.5571  D=0.4404
t=11  A=0.0006  B=0.0008  C=0.5576  D=0.4410
t=12  A=0.0003  B=0.0004  C=0.5578  D=0.4414
t=13  A=0.0002  B=0.0002  C=0.5580  D=0.4416
t=14  A=0.0001  B=0.0001  C=0.5580  D=0.4417


In [9]:

# --------------------------------------------------
# 4. Potencias de P
# --------------------------------------------------

for n in [1, 2, 5, 10, 50]:

    Pn = np.linalg.matrix_power(P, n)

    print(f"\nP^{n}:")
    print(Pn)




P^1:
[[0.3 0.3 0.3 0.1]
 [0.2 0.3 0.1 0.4]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]

P^2:
[[0.15 0.18 0.42 0.25]
 [0.12 0.15 0.19 0.54]
 [0.   0.   1.   0.  ]
 [0.   0.   0.   1.  ]]

P^5:
[[0.02403 0.02943 0.53583 0.41071]
 [0.01962 0.02403 0.28411 0.67224]
 [0.      0.      1.      0.     ]
 [0.      0.      0.      1.     ]]

P^10:
[[0.001155 0.001414 0.557067 0.440363]
 [0.000943 0.001155 0.30145  0.696452]
 [0.       0.       1.       0.      ]
 [0.       0.       0.       1.      ]]

P^50:
[[0.       0.       0.55814  0.44186 ]
 [0.       0.       0.302326 0.697674]
 [0.       0.       1.       0.      ]
 [0.       0.       0.       1.      ]]


In [10]:

# --------------------------------------------------
# 5. Convergencia por punto fijo
# --------------------------------------------------

pi = pi0.copy()

tolerancia = 1e-10
max_iteraciones = 10000

for k in range(max_iteraciones):

    pi_nueva = pi @ P

    error = np.max(np.abs(pi_nueva - pi))

    if error < tolerancia:
        break

    pi = pi_nueva


print("\nDistribución final:")
print(pi_nueva)

print("Iteraciones:", k + 1)
print("Error:", error)


# --------------------------------------------------
# 6. Comprobación
# --------------------------------------------------

print("\npi_final @ P:")
print(pi_nueva @ P)


Distribución final:
[0.      0.      0.55814 0.44186]
Iteraciones: 37
Error: 9.518252852558362e-11

pi_final @ P:
[0.      0.      0.55814 0.44186]
